on: push

name: Update and release

jobs:
  updateDataAndRelease:
    name: Update data and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Chmod
        run: chmod +x ./script/release.sh
      - name: Update data and release
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}